'use client'

import React, { useState } from 'react'
import { ConnectButton } from '@rainbow-me/rainbowkit'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useReadContract, useAccount } from 'wagmi'
import Controller from '../ETHRegistrarController.json'

const Home: NextPage = () => {
	const { address, chain, connector: activeConnector, isConnected } = useAccount()

	const [nameInput, setNameInput] = useState('')
	const { data } = useReadContract({
		abi: Controller.abi,
		address: '0x1DD15613435e374dcEDceDEB275dAe6Fa4DF1A01',
		functionName: 'available',
		args: [nameInput],
	})

	return (
		<div>
			<Head>
				<title>RainbowKit App</title>
				<meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
				<link href="/favicon.ico" rel="icon" />
			</Head>
			<main className="bg-white p-8 rounded-lg shadow-md w-[630px] mx-auto mt-32">
				<div className="container mx-auto space-y-4">
					{isConnected && (
						<div className="flex flex-col space-y-2 mb-12">
							<input
								type="text"
								placeholder="Enter name"
								value={nameInput}
								onChange={(e) => setNameInput(e.target.value)}
								className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:border-blue-500 focus:ring-blue-500 focus:outline-none text-sm"
							/>
							{data?.toString() && <p className="text-gray-600 text-sm">{data.toString()}</p>}
						</div>
					)}

					<ConnectButton />

					<div className="flex items-center space-x-2 text-gray-600 text-sm">
						<span>Address:</span>
						<span>{address}</span>
					</div>

					<div className="flex items-center space-x-2 text-gray-600 text-sm mt-2">
						<span>Wallet:</span>
						<span>{activeConnector?.name || 'Not connected'}</span>
					</div>

					<div className="flex items-center space-x-2 text-gray-600 text-sm mt-2">
						<span>Chain:</span>
						<span>{chain?.name || 'Unknown'}</span>
					</div>
				</div>
			</main>
		</div>
	)
}

export default Home
